version: '3.5'
services:
  milvus-standalone:
    image: milvusdb/milvus:v2.3.3
    container_name: milvus-standalone
    restart: unless-stopped
    ports:
      - "19530:19530"   # Milvus gRPC
      - "9091:9091"     # Milvus HTTP
    volumes:
      - milvus_data:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  milvus_data:
